---
title: "CSCI 5622 Mod 2"
author: "Isaiah Lyons-Galante"
date: "2023-02-23"
output: html_document
---
Setup
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Association Rule Mining Examples
### This example will use the Apriori Alg.
```{r}
library(viridis)
library(arules)
library(TSP)
library(data.table)
#library(ggplot2)
#library(Matrix)
library(tcltk)
library(dplyr)
library(devtools)
library(purrr)
library(tidyr)
## DO THIS ONCE
## FIRST - you MUST register and log into github
## install_github("mhahsler/arulesViz")
## RE: https://github.com/mhahsler/arulesViz

##############
## IF YOUR CODE BREAKS - TRY THIS
##
## Error in length(obj) : Method length not implemented for class rules 
## DO THIS: 
detach("package:arulesViz", unload=TRUE)
detach("package:arules", unload=TRUE)
library(arules)
library(arulesViz)
###################################################################

## To see if you have tcltk run this on the console...
# capabilities()["tcltk"]
library(arulesViz)


## YOUR working dir goes here...
setwd("~/Documents/code/csci5622/mod2")


###################################
## Example 1: Kumar's Beer Example
##
## Dataset: https://drive.google.com/file/d/1BvU3iXtrwxfjBsRShaDgI-Ldh7Y3XSEn/view?usp=sharing
## KumarGroceriesAS_Transactions
##
## ## Dataset:
## HealthyBasket
## https://drive.google.com/file/d/1qaWSTwjrj7tNB43zLss9KC_ecJKp6W4g/view?usp=sharing
###################################################

df <- read.transactions("HealthyBasketData.csv",
                           rm.duplicates = FALSE, 
                           format = "basket",  ##if you use "single" also use cols=c(1,2)
                           sep=",",  ## csv file
                           cols=1) ## The dataset HAS row numbers
inspect(df)

##### Use apriori to get the RULES
FrulesK = arules::apriori(df, parameter = list(support=.35, 
                                                 confidence=.35, minlen=2))
inspect(FrulesK)

## Plot of which items are most frequent
itemFrequencyPlot(df, topN=20, type="absolute")

## Sort rules by a measure such as conf, sup, or lift
SortedRulesK <- sort(FrulesK, by="confidence", decreasing=TRUE)
inspect(SortedRulesK[1:10])
(summary(SortedRulesK))

## Selecting or targeting specific rules  RHS
BeerRules <- apriori(data=df,parameter = list(supp=.001, conf=.01, minlen=2),
                     appearance = list(default="lhs", rhs="Beer"),
                     control=list(verbose=FALSE))
BeerRules <- sort(BeerRules, decreasing=TRUE, by="confidence")
inspect(BeerRules[1:4])

## Selecting rules with LHS specified
BreadRules <- apriori(data=df,parameter = list(supp=.001, conf=.01, minlen=2),
                       appearance = list(default="rhs", lhs="Bread"),
                       control=list(verbose=FALSE))
BreadRules <- sort(BreadRules, decreasing=TRUE, by="support")
inspect(BreadRules[1:4])

## Visualize
## tcltk

subrulesK <- head(sort(SortedRulesK, by="lift"),10)
plot(subrulesK)

plot(subrulesK, method="graph", engine="interactive")
```

Healthy Food Data
```{r}
####################################################
## Example 2: Healthy Food Transaction Data
##
## HERE IS THE DATA - but you should make your own dataset!
## https://drive.google.com/file/d/1qaWSTwjrj7tNB43zLss9KC_ecJKp6W4g/view?usp=sharing
##
##############################################################

Foods <- read.transactions("HealthyBasketData.csv",
                             rm.duplicates = FALSE, 
                             format = "basket",  ##if you use "single" also use cols=c(1,2)
                             sep=",",  ## csv file
                             cols=NULL) ## The dataset has no row numbers
inspect(Foods)

##### Use apriori to get the RULES
Frules = arules::apriori(Foods, parameter = list(support=.35, 
                                          confidence=.35, minlen=2))
inspect(Frules)

## Plot of which items are most frequent
itemFrequencyPlot(Foods, topN=20, type="absolute")

## Sort rules by a measure such as conf, sup, or lift
SortedRules <- sort(Frules, by="lift", decreasing=FALSE)
inspect(SortedRules[1:10])

inspect(SortedRules)
(summary(SortedRules))

################3 Specific Rules

## Selecting or targeting specific rules  RHS
ChocRules <- apriori(data=Foods,parameter = list(supp=.001, conf=.01, minlen=2),
                     appearance = list(default="lhs", rhs="chocloate"),
                     control=list(verbose=FALSE))
ChocRules <- sort(ChocRules, decreasing=TRUE, by="confidence")
inspect(ChocRules[1:4])

## Selecting rules with LHS specified
CarrotRules <- apriori(data=Foods,parameter = list(supp=.001, conf=.01, minlen=2),
                     appearance = list(default="rhs", lhs="carrot"),
                     control=list(verbose=FALSE))
CarrotRules <- sort(CarrotRules, decreasing=TRUE, by="support")
inspect(CarrotRules[1:4])

## Visualize
## tcltk

subrules <- head(sort(SortedRules, by="lift"),10)
plot(subrules)

#plot(subrules, method="graph", engine="interactive")
plot(subrules, method="graph", engine="htmlwidget")
```

