---
title: "hclust"
author: "Isaiah Lyons-Galante"
date: "2023-02-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
# load needed libraries
library(rdhs)
library(tidyverse)
```


## Import Data

### Using the package rdhs
```{r}
# set credentials for accessing DHS API
set_rdhs_config(email = "isaiah.lyons-galante@colorado.edu",
                project = "Machine Learning Class Project")

# download actual datasets
downloads <- get_datasets("SLHR7AFL.ZIP")

# read in the dataset
sl19 <- readRDS(downloads$SLHR7AFL)

# get the variable labels for all column headers
var_labels <- get_variable_labels(sl19)
# head(var_labels) # 3455 rows now, just two columns, variable and description

# export data and labels to CSV for visual inspection and usability in other programs
saveRDS(var_labels, "./data/var_labels.rds")
saveRDS(sl19, "./data/sl19.rds")
```

## Clean up data


### Chop down to 56 variables of interest
```{r}
# read in shortened RDS
sl19 <- readRDS("./data/sl19.rds")
var_labels <- readRDS("./data/var_labels.rds")

# numerical columns of interest
numCols <- c("hv010","hv011","hv012","hv014","hv216")

# filter
sl19num <- sl19[,numCols]
varsNum <- varSec1[numCols,]

# # convert certain columns to factors
# factorCols <- c("hv000","hv001","hv006","hv007","hv024","hv025","hv045c","hv201","hv205","hv206","hv207","hv208","hv209","hv210","hv211","hv212","hv213","hv214","hv215","hv217","hv219","hv221","hv226","hv227","hv230a","hv237","hv241","hv243a","hv243b","hv243c","hv243d","hv243e","hv244","hv246","hv246a","hv246b","hv246c","hv246d","hv246e","hv246f","hv247","hv270","hv270a")
# sl19keep <- sl19keep %>% mutate_at(factorCols, as.factor)

# export to RDS
saveRDS(vars2keep, "./exports/vars2keep.rds")
saveRDS(sl19keep, "./exports/sl19keep.rds")

# write to csv as well
# write.csv(varSec1, "/./exports/varSec1.csv", row.names = FALSE)
# write.csv(sl19sec1, "./exports/sl19sec1.csv", row.names = FALSE)
```

